## Import Dependencies

In [124]:
import pandas as pd
import numpy as np
import ast
from sklearn.model_selection import train_test_split
# from sklearn.metrics import accuray, precison
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

## Load Data

In [102]:
df = pd.read_csv('loan_approval_dataset.csv')
df.head()

,loan_id,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,1,2,Graduate,No,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved
1,2,0,Not Graduate,Yes,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected
2,3,3,Graduate,No,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected
3,4,3,Graduate,No,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected
4,5,5,Not Graduate,Yes,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected

In [106]:
df[' loan_status'] = df[' loan_status'].apply(lambda x:x.strip())

In [123]:
df[' loan_status'].value_counts()

 loan_status
Approved    2656
Rejected    1613
Name: count, dtype: int64

In [6]:
df.isnull().sum()

loan_id                      0
no_of_dependents             0
 education                   0
 self_employed               0
 income_annum                0
 loan_amount                 0
 loan_term                   0
 cibil_score                 0
 residential_assets_value    0
 commercial_assets_value     0
 luxury_assets_value         0
 bank_asset_value            0
 loan_status                 0
dtype: int64

## Brain Storming

In [107]:
# Columns to remove: loan_id, 
df = df.drop(columns=['loan_id'])

In [108]:
df.describe().round(2)

,no_of_dependents,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value
count,4269.0,4269.00,4269.00,4269.00,4269.00,4269.00,4269.00,4269.00,4269.00
mean,2.5,5059123.92,15133450.46,10.90,599.94,7472616.54,4973155.31,15126305.93,4976692.43
std,1.7,2806839.83,9043362.98,5.71,172.43,6503636.59,4388966.09,9103753.67,3250185.31
min,0.0,200000.00,300000.00,2.00,300.00,-100000.00,0.00,300000.00,0.00
25%,1.0,2700000.00,7700000.00,6.00,453.00,2200000.00,1300000.00,7500000.00,2300000.00
50%,3.0,5100000.00,14500000.00,10.00,600.00,5600000.00,3700000.00,14600000.00,4600000.00
75%,4.0,7500000.00,21500000.00,16.00,748.00,11300000.00,7600000.00,21700000.00,7100000.00
max,5.0,9900000.00,39500000.00,20.00,900.00,29100000.00,19400000.00,39200000.00,14700000.00

In [109]:
df[' education'].value_counts()
df[' self_employed'].value_counts()

 self_employed
Yes    2150
No     2119
Name: count, dtype: int64

In [110]:
df[' education'].replace({' Graduate':1, " Not Graduate":0}, inplace=True)
df[' self_employed'].replace({' Yes':1, " No":0}, inplace=True)

C:\Users\test\AppData\Local\Temp\ipykernel_17572\795554930.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[' education'].replace({' Graduate':1, " Not Graduate":0}, inplace=True)
C:\Users\test\AppData\Local\Temp\ipykernel_17572\795554930.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[' education'].replace({' Graduate':1, " Not Graduate":0}, inplace=True)
C:\Users\test\AppData\Local\Temp\ipykernel_17572\795554930.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[' self_employed'].replace({' Yes':1, " No":0}, inplace=True)
C:\Users\test\AppData\Local\Temp\ipykernel_17572\795554930.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[' self_employed'].replace({' Yes':1, " No":0}, inplace=True)

In [57]:
df.head()

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,2,1,0,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved
1,0,0,1,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected
2,3,1,0,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected
3,3,1,0,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected
4,5,0,1,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected

In [111]:
new_df = pd.DataFrame({
    'no_of_dependents': df['no_of_dependents'],
    'education': df[' education'],
    'self_employed': df[' self_employed'],
    'income_annum': df[' income_annum'],
    'loan_amount': df[' loan_amount'],
    'loan_term': df[' loan_term'],
    'cibil_score': df[' cibil_score'],
    'residential_assets_value': df[' residential_assets_value'],
    'commercial_assets_value': df[' commercial_assets_value'],
    'luxury_assets_value': df[' luxury_assets_value'],
    'bank_asset_value': df[' bank_asset_value'],
    'loan_status': df[' loan_status'],
})

In [59]:
new_df.head()

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,2,1,0,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved
1,0,0,1,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected
2,3,1,0,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected
3,3,1,0,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected
4,5,0,1,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected

In [112]:
x = new_df.drop('loan_status', axis=1)
y = new_df['loan_status']

## Train_Test Split

In [113]:
x_train,x_test, y_train,y_test = train_test_split(x,y, random_state=42, test_size=0.20)
display(x_train.shape)
display(x_test.shape)
display(y_train.shape)
display(y_test.shape)

(3415, 11)

(854, 11)

(3415,)

(854,)

## Model Train (Logistic Regression)

In [157]:
def evaluate_model(modelName):
    logistic_model = modelName
    logistic_model.fit(x_train,y_train)
    y_test_pred = logistic_model.predict(x_test)
    recall = recall_score(y_test, y_test_pred, pos_label='Approved')
    accuracy = accuracy_score(y_test, y_test_pred)
    precision = precision_score(y_test, y_test_pred, pos_label='Approved')
    return {'model':modelName, 'accuracy': accuracy, 'precision':precision, 'recall':recall}

In [158]:
list1 = []
LogisticRegression
models = [LogisticRegression(),DecisionTreeClassifier(), RandomForestClassifier() ]
for model in models:
    list1.append(evaluate_model(model))

C:\Users\test\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

## Training Decision Tree

In [163]:
decision_model = DecisionTreeClassifier()
decision_model.fit(x_train,y_train)
y_test_pred = decision_model.predict(x_test)

In [165]:
recall = recall_score(y_test, y_test_pred, pos_label='Approved')
accuracy = accuracy_score(y_test, y_test_pred)
precision = precision_score(y_test, y_test_pred, pos_label='Approved')

In [168]:
accuracy

0.9730679156908665

In [159]:
evaluate_model = pd.DataFrame(list1)
evaluate_model

,model,accuracy,precision,recall
0,LogisticRegression(),0.729508,0.715092,0.945896
1,DecisionTreeClassifier(),0.977752,0.981378,0.983209
2,"(DecisionTreeClassifier(max_features='sqrt', r...",0.977752,0.976059,0.988806

In [164]:
recall = recall_score(y_test, y_test_pred, pos_label='Approved')
accuracy = accuracy_score(y_test, y_test_pred)
precision = precision_score(y_test, y_test_pred, pos_label='Approved')

In [115]:
y_test_pred = logistic_model.predict(x_test)

In [128]:
clss_report = classification_report(y_test, y_test_pred)
conf_matrix = confusion_matrix(y_test, y_test_pred)
print(clss_report)

              precision    recall  f1-score   support

    Approved       0.72      0.95      0.81       536
    Rejected       0.80      0.36      0.50       318

    accuracy                           0.73       854
   macro avg       0.76      0.66      0.66       854
weighted avg       0.75      0.73      0.70       854

In [129]:
conf_matrix

array([[507,  29],
       [202, 116]])

In [170]:
import pickle

with open('decisionTree.pkl', 'wb') as file:
    pickle.dump(decision_model, file)

In [173]:
columns = x.columns


with open('columnName.pkl', 'wb') as file:
    pickle.dump(columns, file)

In [174]:
columns

Index(['no_of_dependents', 'education', 'self_employed', 'income_annum',
       'loan_amount', 'loan_term', 'cibil_score', 'residential_assets_value',
       'commercial_assets_value', 'luxury_assets_value', 'bank_asset_value'],
      dtype='object')